export const LOGIN_REQUEST_INITIATED = "LOGIN_REQUEST_INITIATED"
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_INITIATED"
export const SERVER_SNAPSHOT_RECEIVED = "SERVER_SNAPSHOT_RECEIVED"
export const AUTH_TOKEN_RECEIVED = "AUTH_TOKEN_RECEIVED"
export const USER_URI_RECEIVED = "USER_URI_RECEIVED"
export const LOGOUT_REQUEST_INITIATED = "LOGOUT_REQUEST_INITIATED"
export const LOGOUT_REQUEST_DONE = "LOGOUT_REQUEST_DONE"
export const RESPONSE_STATUS_RECEIVED = "RESPONSE_STATUS_RECEIVED"

export const MARK_VEHICLE_FOR_EDIT = "MARK_VEHICLE_FOR_EDIT"
export const SERVER_VEHICLE_RECEIVED = "SERVER_VEHICLE_RECEIVED"

export const API_REQUEST_INITIATED = "API_REQUEST_INITIATED"
export const API_REQUEST_DONE = "API_REQUEST_DONE"

export const SAVE_ENTITY_REQUEST_INITIATED = "SAVE_ENTITY_REQUEST_INITIATED"
