export const has_mpg_readout_lbl = "Has MPG readout?"
export const has_mpg_readout_explanation = "Whether or not this vehicle is equipped with the ability to display the average miles per gallon (MPG) value."
export const has_mph_readout_lbl = "Has MPH readout?"
export const has_mph_readout_explanation = "Whether or not this vehicle is equipped with the ability to display the average miles per hour (MPH) value."
export const has_dte_readout_lbl = "Has range (DTE) readout?"
export const has_dte_readout_explanation = "Whether or not this vehicle is equipped with the ability to display the range; also known as the distance-to-empty (DTE) value."
export const has_outside_temp_readout_lbl = "Has outside temp readout?"
export const has_outside_temp_readout_explanation = "Whether or not this vehicle is equipped with the ability to display the current outside temperature."
